# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: uuroosterscraper
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

zha:
  zigpy_config:
    network:
      channel: 25       # What channel the radio should try to use.
      channels: [15, 20, 25]  # Channel mask

http:
    use_x_forwarded_for: true
    server_port: 8123
    trusted_proxies:
        - 91.183.46.65
        - 172.16.0.10
        - 127.0.0.1
google_assistant: !include g-assistant-integration.yaml

octoprint:
    host: 172.16.109.63
    api_key: 269D03964F4941F6929AA350CA366D46
    name: Brent
    bed: true
    number_of_tools: 1
    
camera:
  - platform: mjpeg
    name: OctoPrint Ender 3
    still_image_url: http://octopi.local/webcam/?action=snapshot
    mjpeg_url: http://octopi.local/webcam/?action=stream
    
nest: !include google_nest.yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js
homeassistant:
  packages: !include_dir_named include #theme
lovelace:
 mode: storage #use ui-lovelace.yaml
 
#media_extractor:
#    entity_id: media_player.lab1_display
#    media_content_id: https://youtu.be/dQw4w9WgXcQ?t=42
#    media_content_type: music